def mostrar_menu():
    print("===== Gestor de Tarefas =====")
    print("\n1 - Ver Tarefas")
    print("2 - Adicionar Tarefa")
    print("3 - Concluir Tarefa")
    print("4 - Remover Tarefa")
    print("5 - Limpar Todas as Tarefas")
    print("6 - Editar Tarefa")
    print("7 - Pesquisar Tarefas")
    print("8 - Filtrar Tarefas")
    print("9 - Ordenar Tarefas")
    print("10 - Estatísticas")
    print("0 - Sair\n")
